### ISSUE TITLE
Visualize logs in Grafana

### ISSUE THREAD

**Issue by nico110** [springernature/mtcu-mobbing#22]

**Comment by RemkovZ** [comment]
we created a dashboard in Grafana with 2 panels:
1. requests per second for our app instance
2. showing app logs

Dashboard can be found here:
https://mtcu-grafana.apps.private.k8s.springernature.io/d/6LuBqlunk/mtcu-mobbing-metrics?orgId=1

**Comment by jriguera** [comment]
Grafana with Katee dashboards to see app metrics: https://grafana.k8s.springernature.io/d/ME-iJbmnk/katee-app-metrics?orgId=1

(Dashboard is Katte/Katee App Metrics)
